config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users
  root to: 'pages#home'

  resources :users
  resources :boats do
    resources :rentings, only: [ :create, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :rentings
  has_attachments :photos
  validates :name, :address, :kind, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :user
  belongs_to :boat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attachment :avatar
  has_many :boats
  has_many :users
  validates :first_name, :last_name, presence: true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_location
  protect_from_forgery

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end

  private

  def store_location
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :update, :edit, :destroy]

  # Get /boats
  def index
    @boats = Boat.where.not(latitude: nil, longitude: nil)
    unless params[:search][:address].blank?
      @boats = @boats.where(address: params[:search][:address])
    end

    @hash = Gmaps4rails.build_markers(@boats) do |boat, marker|
      marker.lat boat.latitude
      marker.lng boat.longitude
    end
  end

  # Get /boats/1
  def show
    @boat = Boat.find(params[:id])
    @renting = Renting.new
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user = current_user
    if @boat.save
      redirect_to boats_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @boat.update(boat_params)
      redirect_to boat_path(@boat)
    else
      render :edit
    end
  end

  def destroy
    @boat.destroy
    redirect_to boats_path
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :kind, :address, photos: [])
  end

  def set_boat
    @boat = Boat.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

 # skip_before_action :authenticate_user!, only: :home

  def home

  end
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  before_action :authenticate_user!

  def create
    @boat = Boat.find(params[:boat_id])
    @renting = Renting.new(renting_params)
    @renting.user = current_user
    @renting.boat = @boat
    if @renting.save
      redirect_to user_path(current_user)
    else
      render 'boats/show'
    end
  end

  def edit
    @renting = Renting.find(params[:id])
  end

  def update
    @renting = Renting.find(params[:id])
    @renting.update(review_params)
    redirect_to user_path(current_user)
  end



  private
  def renting_params
    params.require(:renting).permit(:starting_date, :end_date)
  end

  def review_params
    params.require(:renting_id).permit(:review_content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @boats = Boat.all
    @bookings = Renting.where(user_id: params[:id])
    @rentings = @bookings.sort_by &:starting_date
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boats/_boat.html.erb
<div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path boat.photos.first.path, height: 250, width: 350, crop: :fill %>')">
  <div class="card-category">
    <p><%= boat.name.capitalize %></p>
  </div>
  <div class="card-description">
    <p><%= boat.address %></p>
    <p> <%= boat.kind %></p>
  </div>
  <div class="card-price">
    <p><%= boat.price %>€/j</p>
  </div>
  <%= link_to "", boat, class: "card-link" %>
</div>

app/views/boats/edit.html.erb
  <div class="form-inputs">

<%= simple_form_for(@boat) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :kind %>
  <%= f.submit "Modifier", class: "btn btn-warning" %>
<% end %>
  </div>

app/views/boats/index.html.erb
<div class="container">
  <h1>
    Voici les bateaux disponibles
    <%= link_to "Retour à la recherche", root_path, class: "btn btn-primary btn-sm" %>
  </h1>

</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <% @boats.first(2).each do |boat| %>
        <%= render "boat", boat: boat %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div id="map" style="width: 100%; height: 515px;"></div>
    </div>
  </div>
  <div class="row">
     <% @boats[2..-1].each do |boat| %>
      <div class="col-sm-4">
        <%= render "boat", boat: boat %>
      </div>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
 </script>
<% end %>

app/views/boats/new.html.erb
  <div class="form-inputs">
<h2>Ajouter votre bateau</h2>
<%= simple_form_for(@boat) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :kind %>
  <%= f.input :photos, as: :attachinary %>

  <%= f.submit "Ajouter un yacht", class: "btn btn-warning" %>
<% end %>
  </div>

app/views/boats/show.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-sm-8 boat-space text-left">
      <div class="boat-description">
        <h1> <%= @boat.name %></h1>
        <p> Port d'attache: <%= @boat.address.capitalize %></p>
        <p> Type de bateau: <%= @boat.kind.capitalize  %></p>
        <div id="price">
          <%= @boat.price %> €/jour
        </div>
      </div>
      <div class="card" >
        <%= cl_image_tag @boat.photos.first.path, height: 250, width: 350, crop: :fill, class: "boat-pictures" %>
      </div>
      <div >
        <ul class="list-inline">
        <% @boat.photos[0..-2].each do |photo| %>
          <li>
            <%= cl_image_tag photo.path, height: 150, width: 200, crop: :fill, class: "boat-pictures" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-sm-4">
      <% if user_signed_in?%>
        <p> Choisissez vos dates et embarquez!</p>
        <%= simple_form_for [@boat, @renting], html: { class: "form-inline" } do |f| %>
          <div class="input-daterange input-group" >
            <%= f.text_field :starting_date, placeholder: 'A partir de', class: 'input-md form-control' %>
            <span class="input-group-addon">to</span>
            <%= f.text_field :end_date, placeholder: 'Jusqu\'au', class: 'input-md form-control'%>
          </div>
          <br>
          <br>
          <%= f.submit "Réserver", class: "btn btn-primary btn-block" %>
        <% end %>
      <% else %>
        <%= link_to "Connectez vous pour réserver", new_user_session_path, class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.2) 50%),url(http://www.solenzara-voile-services.com/medias/images/sense-55-1.jpg);">
  <div class="banner-content">
    <h1>A l'abordage</h1>
    <p>Location de bateaux entre particuliers</p>

     <%= simple_form_for :search, html: {class: 'form-horizontal' }, url: boats_path, method: :get do |f|%>
        <div class="field">
          <%= f.input :address, label: 'Dans quel port louer ?', placeholder: 'Entrez une adresse' %>
        </div>
        <div class="submit_button">
          <%= f.button :submit, 'Je trouve mon bateau', :class => "btn btn-primary btn-lg" %>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="list-inline">
    <li>
      <a href="https://www.facebook.com/" target="_blank">
      <i class="fa fa-facebook-official fa-2x icons" aria-hidden="true"></i>
      </a>
    </li>
    <li>
      <a href="http://www.instagram.com" target="_blank">
      <i class="fa fa-instagram fa-2x icons" aria-hidden="true"></i>
      </a>
    </li>
    <li>
      <a href="https://twitter.com/?lang=en" target="_blank">
      <i class="fa fa-twitter fa-2x icons" aria-hidden="true"></i>
      </a>
    </li>
    <li>
      <a href="https://www.youtube.com/" target="_blank">
      <i class="fa fa-youtube fa-2x icons" aria-hidden="true"></i>
      </a>

  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= "#{controller_name}_#{action_name}" %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_boat.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.avatar? %>
          <%= cl_image_tag current_user.avatar.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= cl_image_tag "http://sergiopardosanchez.com/img/UserMen.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "/users/edit" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Ajouter mon bateau"), new_boat_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <h1>Bonjour <%= @user.first_name.capitalize %></h1>
</div>

<div class="container padded">
  <% @rentings.each do |renting| %>
    <div class="row">
      <div class="col-sm-6">
        <ul>
          <li>
            Vous avez reservé le bateau suivant: <%= renting.boat.name %>
          </li>
          <li>
            Disponible au port de: <%= renting.boat.address %>
          </li>
          <li>
            A compter du: <%= renting.starting_date %>
          </li>
          <li>
            Jusqu'au: <%= renting.end_date %>
          </li>
          <p>
            <%= link_to "Ajouter un avis", edit_boat_renting_path(renting), class: "btn btn-primary" %>
          </p>
        </ul>
      </div>
    <div class="col-sm-6">
      <%= cl_image_tag renting.boat.photos.first.path, height: 250, width: 350, crop: :fill, class: "boat-pictures" %>
    </div>
    </div>
  <% end %>
</div>